---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-s3
  namespace: lb
data:
  # Update Hardware with your MAC/Hostname mapping. Here's mine for an example
  gobetween.toml: |
    [logging]
    level = "info"

    [servers]
    [servers.default]
    protocol = "tcp"
    bind = "0.0.0.0:9001"
    balance = "leastconn"

    [servers.default.healthcheck]
    interval = "3s"
    timeout = "2s"
    fails = 5
    passes = 2
    initial_status = "healthy"
    kind = "ping"

    [servers.default.discovery]
    kind = "static"
    static_list = [
      "192.168.250.11:9001 priority=1",
      "192.168.250.12:9001 priority=1",
      "192.168.250.13:9001 priority=1",
      "192.168.250.14:9001 priority=1",
      "192.168.250.15:9001 priority=1",
      "192.168.250.16:9001 priority=1",
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-s3
  namespace: lb
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: lb-s3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lb-s3
  template:
    metadata:
      labels:
        app: lb-s3
    spec:
      containers:
      - name: lb-s3
        imagePullPolicy: Always
        image: gucio1200/gobetween
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: lb-s3
          mountPath: /etc/gobetween/conf/
        resources:
          limits:
            cpu: "500m" # This could probably be tuned lower
            memory: "512Mi" # This could probably be tuned lower
      volumes:
      - name: lb-s3
        configMap:
          name: lb-s3
---
apiVersion: v1
kind: Service
metadata:
  namespace: lb
  annotations:
    metallb.universe.tf/allow-shared-ip: lb-s3
  labels:
    app: lb-s3
  name: lb-s3
spec:
  ports:
  - name: s3
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: lb-s3
  type: LoadBalancer
  loadBalancerIP: 172.16.99.99
