---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-config
  namespace: lb
data:
  # Update Hardware with your MAC/Hostname mapping. Here's mine for an example
  config: |
    #!ipxe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb
  namespace: lb
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: lb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
      - name: lb
        imagePullPolicy: Always
        image: yyyar/gobetween
        ports:
        - containerPort: 6443
        volumeMounts:
        - name: lb-config
          mountPath: /var/test
        resources:
          limits:
            cpu: "500m" # This could probably be tuned lower
            memory: "512Mi" # This could probably be tuned lower
      volumes:
      - name: lb-config
        configMap:
          name: lb-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: lb
  annotations:
    metallb.universe.tf/allow-shared-ip: lb-svc # If you have a metallb setup, you need this to attach two services to the same IP
  labels:
    app: lb
  name: lb-tcp
spec:
  ports:
  - name: k8s-api
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: lb
  type: LoadBalancer
  loadBalancerIP: 172.16.99.3
