service:
  type: LoadBalancer
  ports:
    - name: k8s-api
      protocol: TCP
      port: 6443
      targetPort: 6443
  loadBalancerIP: "172.16.99.3"

configuration: |
  global
    log stdout format raw local0
    maxconn 1024
  defaults
    log global
    timeout client 60s
    timeout connect 60s
    timeout server 60s

  frontend k8s-api
    bind 0.0.0.0:6443
    bind 127.0.0.1:6443
    mode tcp
    option tcplog
    timeout client 300000
    default_backend k8s-api

  backend k8s-api
    mode tcp
    option tcplog
    option tcp-check
    timeout connect 300000
    timeout server 300000
    balance roundrobin
    default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
    server apiserver1 192.168.2.11:6443 check
    server apiserver2 192.168.2.12:6443 check
    server apiserver3 192.168.2.13:6443 check

containerPorts: []
