---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booty-config
  namespace: booty
data:
  # Update Hardware with your MAC/Hostname mapping. Here's mine for an example
  boot.ipxe: |
    #!ipxe
    set base-url http://pxe/data
    kernel ${base-url}/flatcar_production_pxe.vmlinuz initrd=flatcar_production_pxe_image.cpio.gz flatcar.first_boot=1 ignition.config.url=http://pxe/ignition.json
    initrd ${base-url}/flatcar_production_pxe_image.cpio.gz
    boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booty
  namespace: booty
  labels:
    app: booty
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: booty
  template:
    metadata:
      labels:
        app: booty
    spec:
      containers:
      - name: booty
        imagePullPolicy: Always
        image: gucio1200/algernon:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: booty-config
          mountPath: /srv/algernon
        resources:
          limits:
            cpu: "500m" # This could probably be tuned lower
            memory: "512Mi" # This could probably be tuned lower
      volumes:
      - name: booty-config
        configMap:
          name: booty-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: booty
  annotations:
    metallb.universe.tf/allow-shared-ip: booty-svc # If you have a metallb setup, you need this to attach two services to the same IP
  labels:
    app: booty
  name: booty-tcp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: booty
  type: LoadBalancer
  loadBalancerIP: 172.16.99.2
