apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  releaseName: kube-vip
  chart:
    spec:
      chart: ./charts/kube-vip
      sourceRef:
        kind: GitRepository
        name: kube-vip
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kube-vip-values
