apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelived
  namespace: kube-system
spec:
  releaseName: kubelived
  chart:
    spec:
      chart: ./charts/kubelived
      sourceRef:
        kind: GitRepository
        name: kubelived
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    keepalived:
      image:
        repository: bsctl/keepalived
        pullPolicy: IfNotPresent
        tag: '0.3.0'
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 200m
          memory: 128Mi
      config_path: '/etc/keepalived'
      config_file: 'keepalived.conf'
      health_service_name: 'apiserver'
      health_service_check: '/usr/bin/curl -s -k https://localhost:6443/healthz -o /dev/null'
      health_service_user: 'root'
      health_service_interval: '20'
      health_service_timeout: '5'
      health_service_rise: '1'
      health_service_fall: '1'
      instances:
        - iface: VI_1
          initial_state: 'backup'
          password: 'password'
          router_id: '100'
          advertisement_interval: '3'
          virtual_address: '192.168.250.100'
          interface: 'eth0'
          unicast_peers: []
          health_service_name: 'apiserver'
          health_service_interval: '20'
