---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kube-vip/helm-charts
  ref:
    branch: main

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  chart: ./charts/kube-vip
  sourceRef:
    name: kube-vip
    kind: GitRepository
  interval: 10m
